apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-node-app
  template:
    metadata:
      labels:
        app: auth-node-app
    spec:
      containers:
      - name: auth-node-app
        image: farid25/fm-auth:v1
        ports:
        - containerPort: 8080
          
---
apiVersion: v1
kind: Service
metadata:
  name: auth-node-service
spec:
  selector:
    app: auth-node-app
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort
